var estimoteLocationConstants = {
    GET_ESTIMOTE_LOCATIONS_REQUEST : 'GET_ESTIMOTE_LOCATIONS_REQUEST',
    GET_ESTIMOTE_LOCATIONS_RESPONSE : 'GET_ESTIMOTE_LOCATIONS_RESPONSE',

    GET_ESTIMOTE_LOCATION_REQUEST : 'GET_ESTIMOTE_LOCATION_REQUEST',
    GET_ESTIMOTE_LOCATION_RESPONSE : 'GET_ESTIMOTE_LOCATION_RESPONSE',

    SAVE_ESTIMOTE_LOCATION_REQUEST : 'SAVE_ESTIMOTE_LOCATION_REQUEST',
    SAVE_ESTIMOTE_LOCATION_RESPONSE : 'SAVE_ESTIMOTE_LOCATION_RESPONSE',

    FALSIFY_IS_ESTIMOTE_LOCATION_SAVED : 'FALSIFY_IS_ESTIMOTE_LOCATION_SAVED'
};

module.exports = estimoteLocationConstants;