var gameConstants = {
    GET_GAMES_TODAY_REQUEST : 'GET_GAMES_TODAY_REQUEST',
    GET_GAMES_TODAY_RESPONSE : 'GET_GAMES_TODAY_RESPONSE',

    GET_GAMES_FUTURE_REQUEST : 'GET_GAMES_FUTURE_REQUEST',
    GET_GAMES_FUTURE_RESPONSE : 'GET_GAMES_FUTURE_RESPONSE'
};

module.exports = gameConstants;