var gameConstants = {
    GET_GAMES_TODAY_REQUEST : 'GET_GAMES_TODAY_REQUEST',
    GET_GAMES_TODAY_RESPONSE : 'GET_GAMES_TODAY_RESPONSE',

    GET_GAMES_FUTURE_REQUEST : 'GET_GAMES_FUTURE_REQUEST',
    GET_GAMES_FUTURE_RESPONSE : 'GET_GAMES_FUTURE_RESPONSE',

    SAVE_GAME_REQUEST : 'SAVE_GAME_REQUEST',
    SAVE_GAME_RESPONSE : 'SAVE_GAME_RESPONSE',

    FALSIFY_IS_GAME_SAVED : 'FALSIFY_IS_GAME_SAVED'
};

module.exports = gameConstants;