var offlineConstants = {
    OFFLINE_SAVE_GAME_REQUEST : 'OFFLINE_SAVE_GAME_REQUEST',
    OFFLINE_SAVE_GAME_RESPONSE : 'OFFLINE_SAVE_GAME_RESPONSE',

    OFFLINE_SAVE_TEAM_REQUEST : 'OFFLINE_SAVE_TEAM_REQUEST',
    OFFLINE_SAVE_TEAM_RESPONSE : 'OFFLINE_SAVE_TEAM_RESPONSE',

    OFFLINE_SAVE_PLAYER_REQUEST : 'OFFLINE_SAVE_PLAYER_REQUEST',
    OFFLINE_SAVE_PLAYER_RESPONSE : 'OFFLINE_SAVE_PLAYER_RESPONSE',

    OFFLINE_SAVE_ESTIMOTE_LOCATION_REQUEST : 'OFFLINE_SAVE_ESTIMOTE_LOCATION_REQUEST',
    OFFLINE_SAVE_ESTIMOTE_LOCATION_RESPONSE : 'OFFLINE_SAVE_ESTIMOTE_LOCATION_RESPONSE',

    OFFLINE_SAVE_PLAYER_POSITIONS_REQUEST : 'OFFLINE_SAVE_PLAYER_POSITIONS_REQUEST',
    OFFLINE_SAVE_PLAYER_POSITIONS_RESPONSE : 'OFFLINE_SAVE_PLAYER_POSITIONS_RESPONSE',
};

module.exports = offlineConstants;