var playerConstants = {
    GET_PLAYERS_REQUEST : 'GET_PLAYERS_REQUEST',
    GET_PLAYERS_RESPONSE : 'GET_PLAYERS_RESPONSE',

    GET_PLAYER_REQUEST : 'GET_PLAYER_REQUEST',
    GET_PLAYER_RESPONSE : 'GET_PLAYER_RESPONSE',

    SAVE_PLAYER_REQUEST : 'SAVE_PLAYER_REQUEST',
    SAVE_PLAYER_RESPONSE : 'SAVE_PLAYER_RESPONSE'
};

module.exports = playerConstants;