var teamConstants = {
    GET_TEAM_OF_PLAYER_BY_ID_REQUEST : 'GET_TEAM_OF_PLAYER_BY_ID_REQUEST',
    GET_TEAM_OF_PLAYER_BY_ID_RESPONSE : 'GET_TEAM_OF_PLAYER_BY_ID_RESPONSE',

    GET_TEAMS_REQUEST : 'GET_TEAMS_REQUEST',
    GET_TEAMS_RESPONSE : 'GET_TEAMS_RESPONSE',

    GET_TEAM_HOME_AWAY_REQUEST : 'GET_TEAM_HOME_AWAY_REQUEST',
    GET_TEAM_HOME_AWAY_RESPONSE : 'GET_TEAMS_HOME_AWAY_RESPONSE',

    SAVE_TEAM_REQUEST : 'SAVE_TEAM_REQUEST',
    SAVE_TEAM_RESPONSE : 'SAVE_TEAM_RESPONSE',

    FALSIFY_IS_TEAM_SAVED : 'FALSIFY_IS_TEAM_SAVED'
};

module.exports = teamConstants;