# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Socket.IO-Client-Swift'
pod 'EstimoteSDK', '3.8.0'
pod 'EstimoteIndoorSDK', '2.0.1'
pod 'Alamofire'
pod 'SwiftyJSON'
